#! /usr/bin/env python3

"""
Trabalho 1 da disciplina Seguranca Computacional - CIC

Autores: Luiz Carlos Schonarth Junior
         Bruno Fernandes Teixeira

Universidade de Brasilia
"""

import sys, getopt

def vigenere_cipher(plaintext):
    ciphertext = plaintext
    print('CIPHERED MESSAGE:\n')
    print(ciphertext)

def vigenere_decipher(ciphertext):
    plaintext = ciphertext
    print('DECIPHERED MESSAGE:\n')
    print(plaintext)

def main():
    # Parse command line arguments
    try:
        opts, args = getopt.getopt(sys.argv[1:], "k:cd", ["key=", "cipher", "decipher"])
    except getopt.GetoptError as err:
        print(err) 
        sys.exit(1)
    key = '';
    cipher = True
    for o, a in opts:
        if o in ('-k', '--key'):
            key = a
        elif o in ('-c', '--cipher'):
            cipher = True
        elif o in ('-d', '--decipher'):
            cipher = False
        else:
            print("ERROR: Unhadled option.", file=sys.stderr)
            sys.exit(1)

    if not key:
        key = input("Key: ")

    if not key.isalpha():
        print("ERROR: Key must be alphabetical.", file=sys.stderr)
        sys.exit(1)

    text = sys.stdin.read()

    if cipher:
        vigenere_cipher(text)
    else:
        vigenere_decipher(text)

if __name__ == "__main__":
    main()
