#! /usr/bin/env python3

"""
Trabalho 1 da disciplina Seguranca Computacional - CIC

Autores: Luiz Carlos Schonarth Junior
         Bruno Fernandes Teixeira

Universidade de Brasilia
"""

import sys, getopt 
from typing import List
from string import ascii_lowercase
from math import sqrt

ALPHABET = ascii_lowercase
CHAR_IDX = {x: y for y, x in enumerate(ALPHABET)}

def index_of_coincidence(sequence: str="", frequencies: list=[]):
    sum = 0
    if frequencies:
        for f in frequencies:
            sum += f*f

        return sum

    counts = [0] * len(ALPHABET)
    for char in sequence.lower():
        counts[CHAR_IDX[char]] += 1

    seq_len = len(sequence)
    for n in counts:
        sum += n * (n-1)

    return sum/(seq_len * (seq_len-1))


def cosangle(vec1: float, vec2: float) -> float:
    numerator = 0   
    lengthx2 = 0    
    lengthy2 = 0    
    for i in range(len(vec1)):        
        numerator += vec1[i]*vec2[i]        
        lengthx2 += vec1[i]*vec1[i]        
        lengthy2 += vec2[i]*vec2[i]    

    return numerator / sqrt(lengthx2*lengthy2)


def get_key(ciphertext: str, freq_file: str) -> str:
    lines = open(freq_file).readlines()
    freq_histogram = [float(v) for v in lines] 
    expected_ioc = index_of_coincidence(frequencies=freq_histogram)

    found = False
    key_len = 0
    THRESHOLD = 0.007
    ciphertext = ''.join([c for c in ciphertext if c in CHAR_IDX])

    while not found:
        key_len += 1
        slices = [''] * key_len
        for i in range(len(ciphertext)):
            slices[i % key_len] += ciphertext[i]

        avg_ioc = 0
        for slice in slices:
            avg_ioc += index_of_coincidence(sequence=slice)
        avg_ioc = avg_ioc / key_len

        if avg_ioc >= expected_ioc - THRESHOLD:
            found = True

    frequencies = []
    for i in range(key_len):   
        frequencies.append([0] * 26)
        for c in slices[i]:        
            frequencies[i][CHAR_IDX[c]] += 1   
        for n in frequencies[i]:        
            n /= len(slices[i])

    key = ""
    for freq in frequencies:
        for i in range(len(ALPHABET)):
            histogram = freq[i:] + freq[:i]
            if cosangle(freq_histogram, histogram) > 0.90:
                key += ALPHABET[i]

    return key


def main():
    # Parse command line arguments
    try:
        opts, args = getopt.getopt(sys.argv[1:], "f:m:", ["freq-file=", "method="])
    except getopt.GetoptError as err:
        print(err, file=sys.stderr) 
        sys.exit(1)
        
    freq_file = ""
    method = ""
    for o, a in opts:
        if o in ('-f', '--freq-file'):
            freq_file = a
        elif o in ('-m', '--method'):
            method = a
        else:
            print("ERROR: Unhadled option.", file=sys.stderr)
            sys.exit(1)

    text = sys.stdin.read()
    print(get_key(text, freq_file))


if __name__ == "__main__":
    main()
